const images = {
  bg_splash: require('@res/images/bg_splash.png'),
  bg_list_bottom_overlay: require('@res/images/bg_list_bottom_overlay.png'),
  bg_list_top_overlay: require('@res/images/bg_list_top_overlay.png'),
  bg_tutorial1: require('@res/images/bg_tutorial1.jpg'),
  bg_tutorial2: require('@res/images/bg_tutorial2.jpg'),
  bg_tutorial3: require('@res/images/bg_tutorial3.jpg'),
  bg_tutorial4: require('@res/images/bg_tutorial4.jpg'),
  bg_tutorial5: require('@res/images/bg_tutorial5.jpg'),
  img_def_song_thumb: require('@res/images/default-song-pic.png'),
  ic_menu: require('@res/images/ic_menu.png'),
  ic_header_tv: require('@res/images/ic_header_tv.png'),
  ic_header_tv_gray: require('@res/images/ic_header_tv_gray.png'),
  ic_fuego: require('@res/images/ic_fugo.png'),
  ic_live_video_on: require('@res/images/ic_live_video_on.png'),
  ic_live_video_off: require('@res/images/ic_live_video_off.png'),
  ic_live_audio_on: require('@res/images/ic_live_audio_on.png'),
  ic_live_audio_off: require('@res/images/ic_live_audio_off.png'),
  ic_hash: require('@res/images/ic_hash.png'),
  ic_list_play: require('@res/images/ic_list_play.png'),
  ic_list_chilll: require('@res/images/ic_list_chilll.png'),
  ic_list_apple: require('@res/images/ic_list_apple.png'),
  ic_list_spotify: require('@res/images/ic_list_spotify.png'),
  ic_player_profile: require('@res/images/ic_player_profile.png'),
  ic_player_backward_sm: require('@res/images/ic_player_backward_sm.png'),
  ic_player_forward_sm: require('@res/images/ic_player_forward_sm.png'),
  ic_player_pause_sm: require('@res/images/ic_player_pause_sm.png'),
  ic_player_play_sm: require('@res/images/ic_player_play_sm.png'),
  ic_player_backward: require('@res/images/ic_player_backward.png'),
  ic_player_forward: require('@res/images/ic_player_forward.png'),
  ic_player_pause: require('@res/images/ic_player_pause.png'),
  ic_player_play: require('@res/images/ic_player_play.png'),
  ic_profile_play: require('@res/images/ic_profile_play.png'),
  ic_profile_pause: require('@res/images/ic_profile_pause.png'),
  ic_no_user: require('@res/images/ic_no_user.png'),
  ic_spinner: require('@res/images/ic_spinner.gif'),
  ic_app_loading: require('@res/images/ic_app_loading.gif'),
  ic_tv_loading: require('@res/images/ic_tv_loading.gif'),
  ic_wallet: require('@res/images/ic_wallet.png'),
  ic_sign_dollar: require('@res/images/ic_sign_dollar.png'),
  ic_splash_logo: require('@res/images/ic_splash_logo.png')
};

export default images;